# DataSource Config
server:
  port: 8070

spring:
  application:
    name: spring-common
  datasource:
    # H2 Datasource Config
    #driver-class-name: org.h2.Driver
    #driver-class-name: com.mysql.jdbc.Driver
    #data: classpath:db/data-h2.sql
    #url: jdbc:h2:./springtest

    # MySQL Datasource Config
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema: classpath:db/schema-h2.sql
    url: jdbc:mysql://localhost:3306/web_test?useUnicode=true&characterEncoding=utf8&&useSSL=false
    username: root
    password: 12345678

  # Redis Config
  redis:
    database: 1
    host: localhost
    port: 6379
    password:
    max-active: 200
    max-wait: -1
    max-idle: 10
    min-idle: 0
    timeout: 30000
