# DataSource Config
server:
  port: 8070

spring:
  datasource:
#    driver-class-name: org.h2.Driver
    driver-class-name: com.mysql.jdbc.Driver
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
#    url: jdbc:h2:./springtest
    url: jdbc:mysql://localhost:3306/web_test?useUnicode=true&characterEncoding=utf8&&useSSL=false
    username: root
    password: 12345678